Fix github action

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,7 +3,7 @@ name: Deploy React site to Pages
 on:
   # Runs on pushes targeting the default branch
   push:
-    branches: ["master"]
+    branches: ["master", "main"]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -31,34 +31,34 @@ jobs:
       - uses: oven-sh/setup-bun@v1
         with:
           bun-version: latest
-    
+
       - name: Detect package manager
         id: detect-package-manager
         run: |
-         if [ -f "${{ github.workspace }}/bun.lockb" ]; then
-            echo "manager=bun" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=bun" >> $GITHUB_OUTPUT
-            exit 0
-         elif [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
-            echo "manager=pnpm" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=pnpm" >> $GITHUB_OUTPUT
-            exit 0
-         elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+          if [ -f "${{ github.workspace }}/bun.lockb" ]; then
+             echo "manager=bun" >> $GITHUB_OUTPUT
+             echo "command=install" >> $GITHUB_OUTPUT
+             echo "runner=bun" >> $GITHUB_OUTPUT
+             exit 0
+          elif [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
+             echo "manager=pnpm" >> $GITHUB_OUTPUT
+             echo "command=install" >> $GITHUB_OUTPUT
+             echo "runner=pnpm" >> $GITHUB_OUTPUT
+             exit 0
+          elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
+             echo "manager=yarn" >> $GITHUB_OUTPUT
+             echo "command=install" >> $GITHUB_OUTPUT
+             echo "runner=yarn" >> $GITHUB_OUTPUT
+             exit 0
+           elif [ -f "${{ github.workspace }}/package.json" ]; then
+             echo "manager=npm" >> $GITHUB_OUTPUT
+             echo "command=ci" >> $GITHUB_OUTPUT
+             echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+             exit 0
+           else
+             echo "Unable to determine package manager"
+             exit 1
+           fi
       - name: Setup Pages
         uses: actions/configure-pages@v4
       - name: Install dependencies
